ci:
    submodules: false


repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 20.8b1
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
